// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuooxlwazauwgmxhddsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51b294bHdhemF1d2dteGhkZHNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyMDA2MDUsImV4cCI6MjA4ODc3NjYwNX0.qyNS8X8nWow5eQf-v64P4UlIYE_Lt_EqX9eIFlUewYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});